### ISSUE TITLE
Add healthchecks for API

### ISSUE THREAD

**Issue by idormenco** [code4romania/de-urgenta-backend#102]
API should have healthchecks that will check all the services which are required for the good functionality of API.

Check the Db connection , and credentials for mailing sending service

**Comment by ursaciuc-adrian** [comment]
I'll take this one if it's ok with you.

**Comment by idormenco** [comment]
All yours @ursaciuc-adrian

**Comment by idormenco** [comment]
@ursaciuc-adrian please implement similar to #127
