### ISSUE TITLE
Implement EmailNotificationSender

### ISSUE THREAD

**Issue by decembrya** [code4romania/de-urgenta-backend#107]
Refactor required to extract existing email sending logic to a separate csproj.
This logic can then be used to implement the EmailNotificationSender in the RecurringJobs sln.

**Comment by Laxynium** [comment]
Hi, could I start working on it?

**Comment by idormenco** [comment]
Hi @Laxynium, 
 right now I and @decembrya  are still debating on refactoring so maybe you can pick something like #98 .
Sorry about this.

**Comment by Laxynium** [comment]
Ok, there is no problem. I can pick #98 .
