### ISSUE TITLE
Add concurrency tokens to backpack items

### ISSUE THREAD

**Issue by idormenco** [code4romania/de-urgenta-backend#125]
Multiple users could update the same backpack item so we need a way to handle concurrency.

Add concurrency check.

see [this](https://dejanstojanovic.net/aspnet/2018/november/handling-data-concurrency-in-ef-core-and-aspnet-core-webapi/)

**Comment by VladCuciureanu** [comment]
Hey! I'll take this :)

**Comment by idormenco** [comment]
go go power ~rangers~ @VladCuciureanu
