### ISSUE TITLE
Add refresh token endpoint

### ISSUE THREAD

**Issue by idormenco** [code4romania/de-urgenta-backend#162]
Implement endpoint for refreshing jwt tokens

**Comment by DSVDavid** [comment]
Can I take this one?

**Comment by idormenco** [comment]
sure @DSVDavid

**Comment by evilvodun** [comment]
Still available this issue? I see a opened PR but not approved yet !?

**Comment by idormenco** [comment]
All yours @FlaviusMosneagu
