### ISSUE TITLE
Store and retrieve terms and conditions text

### ISSUE THREAD

**Issue by aniri** [code4romania/de-urgenta-backend#49]
The terms and conditions text should be stored in the db as html.

A `get` endpoint should be used by the frontend apps in order to retrieve it.
Todo:

- [ ] rename LocalizationController to AdminLocalizationController
- [ ] change route to `admin/content`
- [ ] add method `AddOrUpdateContentAsync(AddOrUpdateContentModel model)` to add a new row in  `StringResource table`
- [ ] Add project called `DeUrgenta.Contnent.Api`
- [ ] Add `ContentController`
- [ ] Add a method `GetContentAsync(string key)` see for refference `LocalizationController.GetString`
- [ ] Add a method `GetAvailableContentKeys()` which will return all available keys fo language from `Accept-Language` header
- [ ] Add a method `GetAvailableLanguages()` which will return all available languages

**Comment by DSVDavid** [comment]
Can I take this one?

**Comment by idormenco** [comment]
@DSVDavid all yours! I have updated todo list
