### ISSUE TITLE
[API] Backpack endpoints

### ISSUE THREAD

**Issue by aramboi** [code4romania/de-urgenta-backend#5]
To do:

- [x] CRUD endpoints
- [ ] transfer ownership

**Comment by GabrielMajeri** [comment]
As far as I understand, these were implemented in https://github.com/code4romania/de-urgenta-backend/pull/20? Is there any work left to be done on them?

**Comment by idormenco** [comment]
@GabrielMajeri no real implementation. In that PR I just created endpoints we might need and models + examples. Real implementation and business logic is up for grabs.
