### ISSUE TITLE
Enhance user registration endpoint

### ISSUE THREAD

**Issue by aniri** [code4romania/de-urgenta-backend#56]
Add firstName and lastName in the request body to match the app design https://www.figma.com/file/d6n3MPVRWbL5jP2NmvW96b/De_Urgenta?node-id=1466%3A530

It would be more convenient to store all user info in a single backend call :)

**Comment by idormenco** [comment]
will do

**Comment by GabrielMajeri** [comment]
@idormenco I've tried calling the API through Swagger, and it seems to give me an internal server error when creating a new user:

![image](https://user-images.githubusercontent.com/3010346/118759652-1606d700-b87a-11eb-9e52-270fb568e30e.png)

If I then call it again with the same parameters, it says:

![image](https://user-images.githubusercontent.com/3010346/118759691-2c149780-b87a-11eb-85f1-6fa7473cfbaa.png)

However, no email was sent in either case.

**Comment by idormenco** [comment]
@GabrielMajeri can you try again please ,we released a new version. I do not know if we configured email sending on staging so you can login using your newly created account.

**Comment by GabrielMajeri** [comment]
@idormenco I've tried it again and the error is the same:

![image](https://user-images.githubusercontent.com/3010346/118836398-7a528680-b8cc-11eb-9cd8-47b0090372a0.png)

However, something interesting to note: even though it gave me an error, and I didn't get any email, I was still able to use the `login` API and get a token, without confirming my account. So it seems it gives an error, but creates an account successfully and doesn't require confirmation for it :?
