### ISSUE TITLE
Issue with backpacks API

### ISSUE THREAD

**Issue by GabrielMajeri** [code4romania/de-urgenta-backend#67]
I've been working to implement https://github.com/code4romania/de-urgenta-android/issues/54 and I've encountered some issues with the backpack routes:

- There are two routes which seem to make the same thing, but have different names. Which one should be used for what?

![image](https://user-images.githubusercontent.com/3010346/120767488-e61b2d00-c523-11eb-915c-3b7536788849.png)

- I've tried playing around with the API in Swagger and even though I've set the bearer token correctly I get a bad request response:

![image](https://user-images.githubusercontent.com/3010346/120767601-fdf2b100-c523-11eb-8054-08c88728d53f.png)

(I get the same error code in the Android app while testing)

**Comment by idormenco** [comment]
I improved the documentation on endpoints
* /backpacks -  `Gets backpacks for current user in which he either is contributor or owner`
* /backpacks/my - `Gets backpacks for current user for which he is owner.`
Hope it makes sense

**Comment by GabrielMajeri** [comment]
@idormenco Thank you! But I'm still getting error 400 when trying to play around with the API. I've logged in using Swagger's "Authorize" button and the token from the `/auth/login` route, and it gives me that error when trying to call `/backpacks`.

**Comment by idormenco** [comment]
It might sound weird but can you please create a new account and try again?
It might be that our validators are failing because old accounts do not
have a property set in the Users table.
Sorry for this inconvenience.

**Comment by GabrielMajeri** [comment]
@idormenco Yep, it works now. Thanks for letting me know.
