### ISSUE TITLE
[API] Backpack items endpoints

### ISSUE THREAD

**Issue by aramboi** [code4romania/de-urgenta-backend#7]
To do:

- [ ] CRUD endpoints
- [ ] items must belong to a category and backpack

**Comment by anamarisimo** [comment]
Hey, as vrea sa preiau acest issue (pare ca nu am drepturi ca sa ma pot asigna singura, asa ca las acest comment in loc).

**Comment by idormenco** [comment]
@anamarisimo all yours!
