### ISSUE TITLE
Update new backpack item DTO

### ISSUE THREAD

**Issue by GabrielMajeri** [code4romania/de-urgenta-backend#77]
The new backpack item route currently has the following schema:

![image](https://user-images.githubusercontent.com/3010346/128627871-be76ab4e-7171-4abf-9b88-196b71ac1fa1.png)

However, this doesn't match the data model expected on the front end:
- The name can be made mandatory (non-nullable).
- The expiration date should be optional (nullable) since some items might not expire.
- All the other fields can be marked as required as well.

**Comment by idormenco** [comment]
Thanks for reporting @GabrielMajeri . This is a bug will be fixed in #79.

Can you check again and if it was fixed close this issue ?

**Comment by GabrielMajeri** [comment]
@idormenco the schema looks better now, the only issue left is when I try to create an item with _no expiration date_:

![image](https://user-images.githubusercontent.com/3010346/128754675-508d3a72-bce2-44bf-9d4c-719c6ffabcad.png)

**Comment by idormenco** [comment]
@GabrielMajeri I will create a separate issue with this one. Thanks for reporting.
