### ISSUE TITLE
Possible migration concurrency issue

### ISSUE THREAD

**Issue by GabrielMajeri** [code4romania/de-urgenta-backend#82]
According to [the Microsoft docs](https://docs.microsoft.com/en-us/ef/core/managing-schemas/migrations/applying?tabs=dotnet-core-cli#apply-migrations-at-runtime), the downsides of applying migrations at runtime using `Database.Migrate()` are:
> - If multiple instances of your application are running, both applications could attempt to apply the migration concurrently and fail (or worse, cause data corruption).
> - Similarly, if an application is accessing the database while another application migrates it, this can cause severe issues.

Looking through the code, I've noticed that the recurring jobs project [runs the migrations on startup](https://github.com/code4romania/de-urgenta-backend/blob/09891956f5b91cd2ea9dc8ac86d7fe13e7331155/Src/DeUrgenta.RecurringJobs/Startup.cs#L34), and the infrastructure project [does that as well](https://github.com/code4romania/de-urgenta-backend/blob/09891956f5b91cd2ea9dc8ac86d7fe13e7331155/Src/DeUrgenta.Infra/Extensions/DbExtensions.cs#L20), using the same database context. Additionally, `docker-compose` will try to bring up both containers at the same time, since there's no dependency or ordering constraint between them.

While I haven't yet encountered/reproduced the scenario above, won't it cause problems if some big migrations are added in the future?

**Comment by idormenco** [comment]
Thanks @GabrielMajeri  for spotting this issue. 
I think we should rework this .
Let's keep this as a bug but with lower priority since we still have functionality to add and it is not an issue (yet).
If you have time or want this fixed it's up for grabs.
