### ISSUE TITLE
Backpack ID returned from create backpack item API is only zeroes

### ISSUE THREAD

**Issue by GabrielMajeri** [code4romania/de-urgenta-backend#86]
The backpack ID of each newly created backpack item was included in the response DTO after issue #78 was fixed. However, while testing it now, it seems the `backpackId` is only zeroes:

Request URL: `POST https://api.deurgenta.hostmysite.ro/backpack/1629c040-06bd-4d11-bbff-e94545f69a2a`
Request body:
```json
{
  "name": "Hering conserva",
  "amount": 1,
  "expirationDate": "2023-08-08T00:00:00+00:00",
  "categoryType": 1
}
```

Response body:
```json
{
  "id": "c08903f8-38f4-484a-a6de-0691fd2ab5b9",
  "backpackId": "00000000-0000-0000-0000-000000000000",
  "name": "Hering conserva",
  "amount": 1,
  "expirationDate": "2023-08-08T00:00:00+00:00",
  "categoryType": 1
}
```

`backpackId` is incorrectly zeroed out, instead of containing the correct value.

**Comment by idormenco** [comment]
@GabrielMajeri thanks for spotting. Will be fixed soon
