### ISSUE TITLE
Add unit tests for DeUrgenta.Admin.Api

### ISSUE THREAD

**Issue by idormenco** [code4romania/de-urgenta-backend#92]
Test validators
Test command&query handlers
Test fluent validators

**Comment by ursaciuc-adrian** [comment]
Hello @idormenco ! Long time no see.
Can I take this one?

**Comment by idormenco** [comment]
Hi @ursaciuc-adrian this one is blocked right now by #76 .
But I can recommend other issues:
* #102 pretty straightforward and quick
* #90 easy peasy
* #49 if you want to go from swagger to db.
