### ISSUE TITLE
Limit the number of users in a group

### ISSUE THREAD

**Issue by decembrya** [code4romania/de-urgenta-backend#98]
A group may only contain 30 users.
Make this limit configurable.

**Comment by idormenco** [comment]
@Laxynium all yours

**Comment by idormenco** [comment]
@Laxynium can you please confirm that you are handling this issue

**Comment by Laxynium** [comment]
Yes, I am handling this issue.

**Comment by Laxynium** [comment]
I have created PR https://github.com/code4romania/de-urgenta-backend/pull/114
